<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Authors>benoitrobin</Authors>
    <Product>LOCAL-IA Desktop Manager</Product>
    <NeutralLanguage>fr</NeutralLanguage>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>
